"use client";
import { ChangeEvent, DragEvent, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { FileUp, Loader2, Sparkles } from "lucide-react";
import { startSample, startUpload } from "@/lib/api";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Textarea } from "@/components/ui/textarea";

export default function UploadPage() {
  const router = useRouter(); const input = useRef<HTMLInputElement>(null); const [file, setFile] = useState<File>(); const [goal, setGoal] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const choose = (candidate?: File) => { setError(""); if (!candidate) return; if (!candidate.name.toLowerCase().endsWith(".csv")) return setError("Please choose a CSV file."); setFile(candidate); };
  const submit = async (sample = false) => { setBusy(true); setError(""); try { const mission = sample ? await startSample(goal) : file ? await startUpload(file, goal) : (() => { throw new Error("Upload a CSV or use the sample dataset."); })(); router.push(`/mission/${mission.mission_id}`); } catch (e) { setError(e instanceof Error ? e.message : "Unable to start mission."); } finally { setBusy(false); } };
  return <main className="mx-auto flex min-h-screen max-w-3xl flex-col justify-center px-6 py-16"><div className="mb-10"><div className="mb-4 flex items-center gap-2 text-accent"><Sparkles size={20}/><span className="font-semibold">InsightPilot AI</span></div><h1 className="text-4xl font-semibold tracking-tight">Turn a CSV into trusted decisions.</h1><p className="mt-3 max-w-xl text-slate-500">Upload data, set the question, and watch specialized agents build evidence-backed insights.</p></div><Card><CardContent className="space-y-6"><button type="button" onClick={() => input.current?.click()} onDrop={(e: DragEvent) => { e.preventDefault(); choose(e.dataTransfer.files[0]); }} onDragOver={e => e.preventDefault()} className="flex min-h-48 w-full flex-col items-center justify-center rounded-lg border border-dashed border-slate-300 bg-slate-50 p-6 text-center hover:border-indigo-400"><FileUp className="mb-3 text-accent"/><span className="font-medium">{file ? file.name : "Drop your CSV here"}</span><span className="mt-1 text-sm text-slate-500">or click to browse</span></button><input ref={input} className="hidden" type="file" accept=".csv,text/csv" onChange={(e: ChangeEvent<HTMLInputElement>) => choose(e.target.files?.[0])}/><div><label className="mb-2 block text-sm font-medium">Business goal <span className="font-normal text-slate-400">(optional)</span></label><Textarea value={goal} onChange={e => setGoal(e.target.value)} placeholder="e.g. Identify the strongest regional growth opportunities" rows={3}/></div>{error && <p className="text-sm text-red-600">{error}</p>}<div className="flex flex-col gap-3 sm:flex-row"><Button className="gap-2" disabled={busy} onClick={() => submit()}>{busy && <Loader2 size={16} className="animate-spin"/>}Analyze CSV</Button><Button variant="outline" disabled={busy} onClick={() => submit(true)}>Use sample dataset</Button></div></CardContent></Card></main>;
}
